### ISSUE TITLE
Missing Artwork whilst scrolling.

### ISSUE THREAD

**Issue by adamosborne83** [SerpentDrago/skin.auramod#106]
Hey all,

I am using kodi 19.1
Seren
Venom
Tmdb

When I'm scrolling through list I am now missing the artwork on the left hand side as shown by the box outline.

I have all API's set up and haven't played with any of the settings.

Any ideas? 

http://imgur.com/a/PwwovDp

**Comment by SerpentDrago** [comment]
Clear all cache in seren and run a total cleanup in openwizard. Also rebuild db / Metadata in seren. After rebuild completes restart kodi 

This is some issue with your setup / addon not auramod. Happens if the artwork cache gets fucked up. Especially if it's just seren /one addon. Did you run some automated cleanup tool or utility? Did seren db not properly rebuild? 

The skin is trying to load a clearlogo that no longer exists but thinks is there as the addon is telling it its there

This is only happening with seren right?

**Comment by SerpentDrago** [comment]
@adamosborne83 closing this unless you can add feedback and respond . 

Thanks
