### ISSUE TITLE
[Feature request] Append more items on 'Next' button click

### ISSUE THREAD

**Issue by mrsanor** [SerpentDrago/skin.auramod#141]
So when you have for example seren trending movies list or TMDB trending today list, at the end of page you have buttons for 'Next' and 'Next page' respectively. I guess other addons have similar buttons also with text 'next' in it. 

My question is, when clicking the button on a widget, would it be possible to make it so that instead of following the link and changing the view by opening the next page, it would instead just load and append the items to the already existing movies/shows? Then you would rarely need to leave the main view.

**Comment by inb4after** [comment]
I think this is a Kodi limitation or widget item limit limitation (implementation/performance), else it would work like this anyway.

@SerpentDrago can tell us more about it

**Comment by SerpentDrago** [comment]
skin shortcuts limitation.

Skinshortcuts would have to be completely redesigned. 

Auto widget can do this , well it doesn't append it reloads just that widget to the next "page" .  As it doesn't use skin shortcuts. So you would make a group in AutoWidget then point to that AutoWidget group in the skin . see video below

**Comment by SerpentDrago** [comment]
Example of a Autowidget group with Seren most popular added to it 

https://user-images.githubusercontent.com/21133858/122964425-41875080-d355-11eb-8fe8-de5e0d2ac7b7.mp4

and with minimal   busy loader enabled  in skin settings / misc 

https://user-images.githubusercontent.com/21133858/122965237-fcafe980-d355-11eb-9e3b-49d2e5aad6ee.mp4





You need to make sure the addon in question is supplying at least 20 widgets per page , and  disable auramod's next page button in skin settings and set to say 50 widgets or more

**Comment by drinfernoo** [comment]
@mrsanor For a bit better explanation:

AutoWidget does support "paged widgets" by default, as long as the add-on supplying the path contains a "Next Page" (or similarly named) item at the end. Most add-ons paginate their lists after 20 items, and then add a "Next" item, so you'll need to make sure your widget limit is set to *at least* 21, if not higher, and maybe even higher than that if the add-on fills more than 20 items before pagination (by default or due to settings changes).

AutoWidget will automatically replace the "Next Page" item with one of its own, which will trigger the "paged widget" action, refreshing the widget with content from the next page supplied by the add-on. This happens by default for "Static" and "Cycling" widgets, but there is also a setting to enable it for "Merged" widgets. In this case, any applicable "Next" items will all be sorted to the end of the widget (in whichever order the paths are defined inside the group), but *will not* refresh the widget with new content. In the instance of a merged widget, they will open a media view for the page in question.

Paged widgets which are left on a page besides the first one will be reset to the first page on boot, but this should not happen any other time. Be aware that there was a bug causing the preceding statement to not function correctly, but it has been fixed in AutoWidget 3.2.0.

**Comment by SerpentDrago** [comment]
Ohh and you can install AutoWidget in kodi by following Readme here https://github.com/drinfernoo/plugin.program.autowidget#readme

**Comment by mrsanor** [comment]
Thanks a lot guys, this all was really helpful! I will go ahead and install AutoWidget then.
