### ISSUE TITLE
[Feature request] Force refresh widget

### ISSUE THREAD

**Issue by mrsanor** [SerpentDrago/skin.auramod#142]
There are often times that I know the widget items are out-of-date (eg. tv next up list) but the widget just won't refresh. It would be great if there was a button to force the widget to refresh.

**Comment by jojobrogess** [comment]
You can force them to update by using the ReloadSkin() command. This is available by default from the power menu (press S on keyboard).

Might be easier if you were to keymap that command, so you can use it quicker.

Auto widget has a command you can use, but I am pretty sure it only works with autowidget:

RunPlugin("plugin://plugin.program.autowidget/?mode=force")

I am pretty sure there is an "aggressive refresh" setting option somewhere, but I'm not near my Kodi to find it. Later tonight I'll post where it is if I can find it.

**Comment by jojobrogess** [comment]
Skin Helper Service Widgets Settings:
![2021-06-18 18_55_12-Greenshot](https://user-images.githubusercontent.com/17692472/122627813-e27cbf80-d066-11eb-8a59-7d49ec728c7d.png)
I would care to assume that this only works with skin helper service widgets, and it doesn't force a refresh but it might help with mitigating your need to force.

If it's an autowidget use:
`RunPlugin("plugin://plugin.program.autowidget/?mode=force")`

But this command setting should refresh everything within the skin:
`ReloadSkin()`
 

I do agree that it would be nice to have a feature that ONLY refreshes widgets rather than the skin as a whole, so you don't get bumped off whatever you were doing or wherever your cursor was.  Because as of now, that's what happens if you use  `ReloadSkin()`. It just restarts the whole skin.

**Comment by inb4after** [comment]
Yes there should be a setting in your addon to refresh the widgets after you watch something, but for manual refreshing you can use:

1\. Label: `Reload skin` Action: `ReloadSkin()`
2\. Label: `Update Widgets + Library` Action: `UpdateLibrary(Video)`

I think 2 only works for library items. So 1 is what you should be using for addon widgets anyway. 

To open the power menu anywhere you can just hold back (already the default keybind) on your remote.

**Comment by SerpentDrago** [comment]
setting a custom action to  >   UpdateLibrary(Video) 
 will force a In page refresh of any skin shortcuts widgets even if from addons FYI :) 

Much better then reload skin if all you want to do is trigger a widget reload .  you will see the little loading icon in the top right . and the only thing that you will notice is the widgets reload in place .

**Comment by SerpentDrago** [comment]
I used to set a Category widget in each main menu  section to this , so i could easily refresh widgets . Use however you want  simply  make choose action > custom action >  and put in  UpdateLibrary(Video)  



Also FYI the skin already does a updatelibrary action , after video playback to enable the refresh of home page Next up style widgets :) and most addons do it also . Just understand as this reloads all widgets , its very demanding and hits lots of meta data servers depending on where the addon / widget is pulling from .  don't' go spamming it !
