### ISSUE TITLE
[Bug] Favorites content not loading on the widgets menu.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SerpentDrago/skin.auramod#212]
Hey there, its been a long time and its good to see you. I had a question about the favorites Widget and i can't tell if its a bug or its not added. Whenever you add favorites in your Configured Widgets, you don't see them on the menu for some odd reason. 
![image](https://user-images.githubusercontent.com/62456796/139613606-8e8d0202-bba7-402c-a4be-b8ffb4bd2c1f.png)
On here where it says content loading, it doesn't load your stuff in favorites. I'm not sure if this is a bug but if you can take a look at this, that would be great. 

Steps to reproduce
1. Add a movie or tv show or video to favorites 
2. Go on the settings page to Menu & Widgets and add a favorites Menu.
![image](https://user-images.githubusercontent.com/62456796/139613914-14216847-4075-49f8-b19e-b19b577f048a.png)
3. Go to configure Widgets
4. Add favorites as your action. 
![image](https://user-images.githubusercontent.com/62456796/139614004-d5d93c8b-2779-4403-a0b4-5c5aaa269ad3.png)
5. Go all the way back and see the favorites menu.
6. Notice that content never loads on favorites.

**Comment by Goldenfreddy0703** [comment]
Hey so i kinda felt really dumb and thought this was a bug but i see why its like that now cause favorites could be anything it wants and i understand thanks to drinfernoo's reddit post. 
https://www.reddit.com/r/Addons4Kodi/comments/b3mev2/adding_a_widget_to_my_favourites_menu/

Thank you so much for making this wonderful skin and you guys are the best.

**Comment by pujionodk** [comment]
Hi, You can add favourites content to widget using skin helper service widget

![image](https://user-images.githubusercontent.com/41060630/147401628-aed79c8e-c57b-4164-a073-af8434fbe7a1.png)

1. choose your favourite menu.
2. configure submenu / category widget.
- add random item with action
- disable it.
3. configure widgets
- add widget > choose widget > add-on > video add-on > skin helper service widget > favourites > favourites > Use as widget

Step number 2 not required when I still use auramod 1.1.0
Since auramod 1.1.x update or maybe skin helper service update (I don't remember which one), my favourites folder disappear, I tried one week to found that workaround. 
Disabled the submenu/category so it not showing in favourites menu page, but if you don't have submenu item, the widget not showing in favourite menu page.

**Comment by Goldenfreddy0703** [comment]
Hey @pujionodk sorry I never got your reply but I will try that and see if it works. 

Thank you so much
