### ISSUE TITLE
[Feature Request] Show season art in Episode List View

### ISSUE THREAD

**Issue by Viper67857** [SerpentDrago/skin.auramod#234]
There's currently a large area of dead space below the current season label, which would be a perfect place for the season poster. Here's a hack job preview I did on my phone: https://imgur.com/a/UJi4Rfq

**Comment by jojobrogess** [comment]
I don't know what I'm doing, but I'm almost there lol 

![2022-02-19 22_57_53-Greenshot](https://user-images.githubusercontent.com/17692472/154832173-27f243e1-788d-4f65-8937-efb64b9f3191.png)

atm trying to figure out how I got it to display in the first place and then how I can adjust the size to fit in the space accordingly. 

we'll see if I can do it, highly doubt it lol

**Comment by xyzfre** [comment]
You definitely got the right idea looking pretty good so far👏🏼

**Comment by jojobrogess** [comment]
If I'm reading the code correctly, I can't modify it in an easy way, at least not if we want this to get this pushed to everyone.  

All of the existing code is "linked" to show certain container.id's (the pages you see in the skin) and I don't think it would be advised to change that code just for it to work on this new section.

 To display a poster in a specific size, I would have to create a new `View_Library_Poster_Medium` and a new `Object_MediumPoster`.

Yeah, so basically I can barely read this stuff let alone understand it.
this is getting fun lol 

***********************************************************************************************************************************

![2022-02-20 20_51_40-Greenshot](https://user-images.githubusercontent.com/17692472/154891414-9299aff1-7bc7-4ee2-ac18-49e5ad5f1e66.png)

atm I'm using `diffuse/widgetposter.png` as it seems like the only thing that's close enough to the right size. 

Just gotta move it around a little, then gut the code until everything else is gone and the new stuff remains. 
I really wish I knew what I was doing lol

**Comment by jojobrogess** [comment]
Got it. Kinda. 
I know this IS NOT how it should be coded. but it looks fine'ish.

***********************************************************************************************************************************

![2022-02-20 21_49_43-Greenshot](https://user-images.githubusercontent.com/17692472/154896902-b4570c97-f42c-416f-9fdf-120618b70a6c.png)

Let me know if this looks good to you and I'll get a branch made.

**Comment by Viper67857** [comment]
Looks great 👍

**Comment by jojobrogess** [comment]
[Fix4-Includes_View_Posters](https://github.com/jojobrogess/skin.auramod/tree/Fix4-Includes_View_Posters)
This should add Season Art to Episode Viewlist(Netflix Homestyle)

***********************************************************************************************************************************

@SerpentDrago & @inb4after let me know how ugly this is lol

**Comment by lebigboss** [comment]
@jojobrogess Beautiful, thank you

**Comment by lebigboss** [comment]
@jojobrogess I have this problem
![Screenshot_20220224-141538](https://user-images.githubusercontent.com/12912677/155617765-631adfdd-6e6c-4fec-9674-72490abe8e19.png)

**Comment by xyzfre** [comment]
> @jojobrogess I have this problem
> 
> ![Screenshot_20220224-141538](https://user-images.githubusercontent.com/12912677/155617765-631adfdd-6e6c-4fec-9674-72490abe8e19.png)
> 
> 

You have to go into Kodi settings ,Media Settings,, General and disable Show parent folder items that should fix your issue🤞🏼

**Comment by jojobrogess** [comment]
@xyzfre is correct, changing that setting should remove the parent folder icon that's displaying.


BUT it looks like from the photo you posted, I wrote the code wrong. I didn't think about widget aspect in respect to widget image profile.(or maybe it's carrying over something, honestly idk what I'm doing, I'm winging it over here lol)

In your photo you can see the "background" imageblur effect for season poster being displayed, when the episode image is in landscape. 

I'll try to take a look at this tonight

**Comment by jojobrogess** [comment]
@lebigboss where are you looking from?
I can't get my auramod to display episode art as season art in episode view mode `Episode List`.

It looks like you're looking in a list within a list inside an addon(TMDBHelper,Seren.EmbuaryInfo,...)
Walk me through how you got to that page, and maybe I can figure out why it's displaying like that. 

**********************************************

I am also curious as to what `List` and `Info List` look like for episode `View Mode`.
Is it displaying the seasonal art or episode art?

**Comment by lebigboss** [comment]
@jojobrogess  It's the episode art, in Auramod you just need to uncheck this setting
<img width="939" alt="Screenshot_6" src="https://user-images.githubusercontent.com/12912677/155675626-f3dc1ff7-b49c-47eb-b2a4-fdde13127e67.png">


<img width="928" alt="Screenshot_7" src="https://user-images.githubusercontent.com/12912677/155675821-5d9bde48-743e-46de-98cb-b5b9fc0fe750.png">


And I think the problem is from the addon, I disabled Show parent folder but nothing change
<img width="942" alt="Screenshot_8" src="https://user-images.githubusercontent.com/12912677/155676211-1ef1e562-6f5d-4e54-bf00-262914a03703.png">

It's a french addon for movies and tv show like Seren.
Thx for your help

**Comment by jojobrogess** [comment]
What is it called? 
Do you have the URL/GitHub? 

I'll take a look at it and see what's going on.

**Comment by lebigboss** [comment]
@jojobrogess  no they don't have github
https://cdn.discordapp.com/attachments/928939486220525589/944904563809484822/plugin.video.sendtokodiU2P-0.5.20.6.zip

**Comment by jojobrogess** [comment]
I went through the files and it looks like it does have a GitHub, but I can't tell if the version you sent me was modified from the GitHub version. I'm on my cell reading through the files.

https://github.com/firsttris/plugin.video.sendtokodi


I'll double check everything and post an update later on tonight if I find anything substantial. 

Thanks for the quick reply!

**Comment by jojobrogess** [comment]
The setting @xyzfre and I mentioned, was because of the picture you posted:
![Inked155617765-631adfdd-6e6c-4fec-9674-72490abe8e19_LI](https://user-images.githubusercontent.com/17692472/155827173-2a9168ef-79a0-49f0-b6ec-525c9a1697a7.jpg)

THAT Top Folder Icon, if you select it, will take you to the parent folder. 
The setting we were talking about, removes it. 

***************************************************

SendToKodi plugin receives URLs and resolves almost all of them with [yt-dlp](https://github.com/yt-dlp/yt-dlp) creating a playable video stream for kodi.

AS for your plugin. That's was interesting. As well half in french, like code wise, and I don't speak french lol
It looks like your plugin is a modification of [plugin.video.sendtokodi](https://github.com/firsttris/plugin.video.sendtokodi), it might be modifying it on the fly or using it as a resource, I'm not certain why it needs `.pyc` files. Regardless...

********************************************

I can see that in service.py on line `1789`:

>def prepareUpNext(title, numId, saison, episode):
    notice(episode)
    sql = "SELECT link FROM tvshowEpisodes \
            WHERE numId={} AND saison='Saison {}' AND episode=='S{}E{}'".format(numId, str(saison).zfill(2), str(saison).zfill(2), str(int(episode) + 1).zfill(2))
    link = extractMedias(sql=sql, unique=1)
    notice(link)
    next_info = {}
    if link:
        try:
            mdb = TMDB(__keyTMDB__)
            tabEpisodes = mdb.saison(numId, saison)
            #['Épisode 1', 'Maud Bachelet semble vivre une vie parfaite ', '2022-01-10', '/jkV6JVxXIiDujhEyFreyEo5IxUe.jpg', 0.0, 1, 1]
            if [x for x in tabEpisodes if x[-1] > int(episode)]:
                next_info["current_episode"] = [dict([
                    ("episodeid", x[-1]),
                    ("tvshowid", 0),
                    ("title", x[0]),
                    ("art", {
                        'thumb': "http://image.tmdb.org/t/p/w500%s" %x[3],
                        'tvshow.clearart': "",
                        'tvshow.clearlogo': "",
                        'tvshow.fanart': "",
                        'tvshow.landscape': "http://image.tmdb.org/t/p/w500%s" %x[3],
                        'tvshow.poster': '',
                    }),
                    ("season", x[-2]),
                    ("episode", x[-1]),
                    ("showtitle", title),
                    ("plot", x[1]),
                    ("rating", x[-3]), ("firstaired", x[2])]) for x in tabEpisodes if x[-1] == int(episode)][0]
                next_info["next_episode"] = [dict([
                    ("episodeid", x[-1]),
                    ("tvshowid", 0),
                    ("title", x[0]),
                    ("art", {
                        'thumb': "http://image.tmdb.org/t/p/w500%s" %x[3],
                        'tvshow.clearart': "",
                        'tvshow.clearlogo': "",
                        'tvshow.fanart': "",
                        'tvshow.landscape': "http://image.tmdb.org/t/p/w500%s" %x[3],
                        'tvshow.poster': '',
                    }),
                    ("season", x[-2]),
                    ("episode", x[-1]),
                    ("showtitle", title),
                    ("plot", x[1]),
                    ("rating", x[-3]), ("firstaired", x[2])]) for x in tabEpisodes if x[-1] == int(episode) + 1][0]
>
There is no definition for season art. Or only looks up landscape art? 

*************************************************************************

I don't have the 3 services it requires to run the addon, so I can't mess around with the code and see what happens lol
Maybe you can try to notify the devs? And they can add in the code. It's hard to fix something I can't even run.
Sorry I wasn't much of help 

But as far as I know, the episode modification should work through other addons/plugins as long as they can supply season art or default to poster image style rather than landscape.

**Comment by jojobrogess** [comment]
HEY @lebigboss , it looks like [TheMovieDBHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper) just issued an update that might cover your addon displaying landscape art as season art.

It looks like the top half of the convo was about french art through tmdbh's new language/art update, and some bugs.
(Bottom half is about aura homestyle landscape panel clearlogo always appearing regardless of skin settings)

**************************************************

The comment that caught my eye:

_Originally posted by @matke-84 in https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/654#issuecomment-1047281704_
>I would change only one thing. For season specific lendsacape I would leave fanart.tv when is turned on prefer artworks from tmdb. TMDb landscape images are actually language backdrops. Tmdb doesn't have landscape images for the seasons but since we set as fallback those images then display them now.

**************************************************

[blacklist landscape tmdb_art for seasons #654 ](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/ebb265e2a2bbdcae39907a9215655bd2dd8e6b4e) <--commit
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/654 <--issue

**************************************************

It might cover your use case, if you have your settings like that. 
And since I can't test out if it did fix it, I thought I'd mention it.
If it does fix it, let me know. Because that would be awesome lol

**Comment by meesterexx** [comment]
> [Fix4-Includes_View_Posters](https://github.com/jojobrogess/skin.auramod/tree/Fix4-Includes_View_Posters) This should add Season Art to Episode Viewlist(Netflix Homestyle)
> 
> @SerpentDrago & @inb4after let me know how ugly this is lol

FYI, in testing this, I noticed there was a smaller poster outline showing inside the poster:
![outline](https://user-images.githubusercontent.com/13154733/156019174-e4bb35d8-1d14-4753-8d0c-2bfc822976f0.png)

I commented out lines 311-313 in Includes_View.xml to get rid of it
`                `
After edit:
![no-outline](https://user-images.githubusercontent.com/13154733/156019381-fcf661aa-7915-40bd-97e4-3b69c3982ad5.png)

**Comment by jojobrogess** [comment]
@meesterexx  THANK YOU!!!

new update with fixed code here:

https://github.com/jojobrogess/skin.auramod/tree/Fix4-Includes_View_Posters

**************************************************************

FROM:
>    <include name="View_Library_Poster_Medium">
        <control type="group">
            <left>50</left>
            <bottom>view_pad</bottom>
            <top>420</top>
            <visible>Container.Control.IsVisible(502) | Control.HasFocus(502)</visible>
            <control type="group">
                <width>widget_poster_width</width>
                <height>widget_poster_height</height>
                <control type="image">
                    <texture colordiffuse="Background" border="20">common/box.png</texture>
                    <visible>Control.IsVisible(58)</visible>
                </control>
                <include content="Defs_PosterBack">
                    <param name="pad" value="-10" />
                </include>
                <include content="Object_MediumPoster">
                    <param name="discart" value="false" />
                </include>
                <control type="group">
                    <top>-10</top>
                    <right>-10</right>
                    <visible>Control.IsVisible(58)</visible>
                    <include>View_WatchedOverlay</include>
                </control>
                <control type="image">
                    <texture colordiffuse="PixelLines" border="20">common/outline.png</texture>
                </control>
                <control type="group">
                    <left>-10</left>
                    <right>-10</right>
                    <bottom>-10</bottom>
                    <top>-10</top>
                    <visible>Control.HasFocus(58)</visible>
                    <include>View_Selectbox</include>
                </control>
            </control>
        </control>
    </include>

**************************************************************

TO:
>    <include name="View_Library_Poster_Medium">
        <control type="group">
            <left>50</left>
            <bottom>view_pad</bottom>
            <top>420</top>
            <visible>Container.Control.IsVisible(502) | Control.HasFocus(502)</visible>
            <control type="group">
                <width>350</width>
                <height>550</height>
                <control type="image">
                    <texture colordiffuse="Background" border="20">common/box.png</texture>
                    <visible>Control.IsVisible(502)</visible>
                </control>
                <include content="Defs_PosterBack">
                    <param name="pad" value="-10" />
                </include>
                <include content="Object_MediumPoster">
                    <param name="discart" value="false" />
                </include> 
            </control>
        </control>
    </include>

**************************************************************

PLEASE let me know if I added more bugs lol

**Comment by mason1171** [comment]
Bookmark

**Comment by jojobrogess** [comment]
@inb4after is there any way this feature request can get merged in, as well? 
I haven't seen any bugs from this change and no one has reported anything since I posted this. 

It also seems to be a great addition for that view type.

https://github.com/jojobrogess/skin.auramod/tree/Fix4-Includes_View_Posters

I can create an updated PR for this too, just let me know

**Comment by jojobrogess** [comment]
I think I got something wrong somewhere, and I don't know how I didn't notice it before
(maybe it's because I'm using Nexus atm and it wasn't loading in before)

But if you have a semi played file it will show the episode thumb
(unless you have `Use TV Show fanart for Episodes` selected in skin settings) in the season art spot breaking some logic:

![2022-06-30 19_23_02-Greenshot](https://user-images.githubusercontent.com/17692472/176811353-eb079c8c-2124-477e-9ed3-7acd12adb07a.png)

The shader box's size needs to be set conditionally based on the output.
ie: that size when season art is being displayed, and another when `UseTVShowfanartforEpisodes` is not enabled for in progress TV Shows.

I'll see if I can do this.

***********************************************************************************************************

ALSO FYI
If you downloaded this from my branch and want more of the fixes that have come out since I originally posted it, just re-download it from the same [branch](https://github.com/jojobrogess/skin.auramod/tree/Fix4-Includes_View_Posters) 
(! others have different fixes and some are broken).

I have merged and updated the branch to keep it current with this one. 
And will continue to do so until/if the feature is added in.
