### ISSUE TITLE
Kodi crashes 

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#247]
Since updating to 19.4 kodi crashes after any skin reload, and Upton start up when loading widgets , would this be related to auramod?

**Comment by jojobrogess** [comment]
I never experienced anything like this while on 19.4.

Try to post clean logs with only the crash.

More than likely it's your how 19.4 works with your OS, your install, your network, or your addons. 
Since 19.3 works without the same issue, it's probably outside of the skin. 

I do know that jurialmunkey and Angelinas1 have updated their scripts a little bit recently, slightly changing how things work. 
Make sure you have those updated as well, since themoviedbhelper, skin.helper.service/widgets, metadatautils are core components of the auramod skin. 

AS WELL, if you're running autowidget, that has also been updated recently.

BUT I doubt ANY of their code would cause a crash.

**Comment by JFG1000** [comment]
Please could you point me in the right direction of how i can get them updated? Many thanks

**Comment by jojobrogess** [comment]
If you don't know how, it's not advised to update through the .zip method since the addons wouldn't update after that.(you'd have to reselect to them from their respective repo)(plus I'm at work atm, I don't have any urls or kodi open to help direct you through the process)

Would be smarter to wait for them to be updated through their repositories, and then allow kodi to self update them. 

But even then, like I said, it's more than likely not because of those. 

Posting a clean log(one only with you opening kodi and getting it to crash) will help. Without it, it's a shot in the dark. 
Unless you can provide a video of the crash, but even then that'll only show part of the problem.

**Comment by JFG1000** [comment]
Just an update to this post, the crashes have now stopped as they were the cause of an addons newest update which has now been fixed, many thanks for the help

**Comment by jojobrogess** [comment]
Oh awesome, glad everything worked out. 

What addon was it?

**Comment by JFG1000** [comment]
Thanks, was Fen. Has Auramod stopped development now?

**Comment by jojobrogess** [comment]
Yeah it looks like SerpentDrago has stepped away from active development for the time being. 

And inb4after, just came in before but hasn't come in after.(sorry had to lol) idk where he's at. 

But yeah, active development has stopped for Auramod. 


I am trying to keep it alive, but it's hard considering I don't know how fix/update any components.

**Comment by JFG1000** [comment]
I respect both there decisions to be honest, gutted but it is what it is, Auramod still is a great skin and it's working great for how I use it, so all the time it is working for me, I shall continue to use it I think.
