### ISSUE TITLE
WidgetBar Items Cache

### ISSUE THREAD

**Issue by HairyHook** [SerpentDrago/skin.auramod#272]
Hi there!

Thank you for the fantastic work with the skin. I have a quick question, are the WidgetBar items being cached? Asking specifically for the ratings. Whenever I switch between items (either shows or movies), all ratings disappear and sometimes they take a while to load. This makes me think that ratings are not being actively cached. Is that the case? Is it possible to cache them and make the api query update in the background so it updates the cache? I don't know how it works, so it might not even be possible. 

Thanks again.

**Comment by inb4after** [comment]
Ratings are handled by [TMDbHelper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper) and its [service monitor](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor) feature. It does cache ratings from TMDb and OMDb in a local database which are updated when item properties are refreshed periodically. It caches all previously looked up item properties, to improve speed when it is looked up later on.

Items from addons other than TMDbHelper (including library items) need to wait for the service monitor to acknowledge the newly selected item, which then triggers the property lookups. It checks if the properties exist in the database already or if a certain amount of time has passed since the last check, before doing a new lookup.

Items from TMDbHelper itself don't need to wait for the service monitor to acknowledge the new item. Some ratings like TMDb ratings which are fetched in the same API call as the list you are viewing can be displayed instantly and are usually the most updated. You can test this by opening a TMDb list from this addon and seeing if there is a timing difference.

AuraMOD uses variables to dynamically switch between whichever property is available first, which is usually instant. The delay upon switching items is probably caused by the service monitor, as we need to wait for the selected item details before looking up properties for it.

It could also be that Kodi itself struggles with looking up and/or retrieving custom item properties, which can be easy to notice on lower end devices or slower network speeds. For example, a high-end PC will almost always be many times faster overall than a device like the NVidia Shield.

If you would like a more accurate and in-depth understanding of how it all works you could post this same question on the [TMDbHelper issues](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues) page, @jurialmunkey created the addon and would be able to help us figure it out.

**Comment by HairyHook** [comment]
Appreciate the detailed explanation, @inb4after!! For the record, all my widgets are coming from TMDBHelper, so I will reach out to @jurialmunkey to see if he has any idea.
