### ISSUE TITLE
[BUG]Missing Playback indicator and Unwatched count.

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/skin.auramod#299]
On this screen "My Lists 1" using Hubs the 1st show poster is missing 'Playback indicator' Pie and the 3rd show is missing 'Unwatched Count' both are instead blank.  

![Kodi_20240914_161348](https://github.com/user-attachments/assets/59b475e6-6c04-44ef-93bf-491e68f37f68)

Kodi 21.1
Seren 3.0.0 (Fork Patch)
AuraMOD 2.0.4

**Comment by inb4after** [comment]
The fix should now be live, but due to the nature of the bug I had to backport the changes to all versions of AuraMOD.

Could you now re-install the skin from `Addons > My add-ons > All > AuraMOD > Versions > Select latest version from repository` and test if the issue still occurs.

If you still have the issue after re-installing, it's possible that Kodi has installed the skin from the local package cache instead of the repository where the updated .zips are.

To fix this, navigate to `...\addons\packages` and delete `skin.auramod.zip` before trying to install again.

**Comment by inb4after** [comment]
As for partial progress indicator (pie), this is reserved for partially played episodes.

TV show unwatched episode count behavior in hub lists should now be fixed and match the homescreen lists behavior.

**Comment by Dealz-416LS** [comment]
> As for partial progress indicator (pie), this is reserved for partially played episodes.

Your right that makes sense, these are TV Show posters.

> TV show unwatched episode count behavior in hub lists should now be fixed and match the homescreen lists behavior.

Fixed.

![Kodi_20240919_144522](https://github.com/user-attachments/assets/5d10417d-9cfa-4bf8-9dde-b0ba934ae045)
