### ISSUE TITLE
Missing clear logos in panel view for Fen and POV

### ISSUE THREAD

**Issue by Ghostwithoutashell** [SerpentDrago/skin.auramod#301]
This oddly only happens when when using TMDb to get the images, switching to extra art resolves the issue. Images and settings can be provided if required.

**Comment by inb4after** [comment]
Please send screenshots of the issue.

**Comment by Ghostwithoutashell** [comment]
![Screenshot 2024-09-18 093808](https://github.com/user-attachments/assets/6a9fd44a-983e-4381-b7b0-cedff0659572)
![Screenshot 2024-09-18 093744](https://github.com/user-attachments/assets/08fc32ca-8cfa-4492-8ed8-84f93563ed32)
![Screenshot 2024-09-18 093707](https://github.com/user-attachments/assets/438ead7e-7935-4b47-a0e0-f85b13e352c5)
![Screenshot 2024-09-18 094036](https://github.com/user-attachments/assets/0d4d4c7b-c5ee-4e45-80dd-457e56fcf0da)

**Comment by Ghostwithoutashell** [comment]
![Screenshot 2024-09-18 093843](https://github.com/user-attachments/assets/3093de0c-8221-4c69-9c96-72a154fe7ce0)


Also some weird things that happen 
1. in the widget in the home page the clear Logos is just ifne
2. when using TMDb as the option and you open the setting pane the Clear logos shows up in panel view you can see around the settings. 

This could all be resolved by a fresh install or it could be a weird quirk who knows haha.

**Comment by inb4after** [comment]
Could you check Skin Settings > Widgets > Enable Clearlogos on Widgets?

**Comment by Ghostwithoutashell** [comment]
It is enabled, i even toggled it on and off hoping it would resolve it before opening the ticket

**Comment by inb4after** [comment]
I have reproduced the issue using a different addon, I will look into it as it must be a skin issue then.

**Comment by Ghostwithoutashell** [comment]
awesome thanks

**Comment by inb4after** [comment]
The fix should now be live, but due to the nature of the bug I had to backport the changes to all versions of AuraMOD.

Could you now re-install the skin from `Addons > My add-ons > All > AuraMOD > Versions > Select latest version from repository` and test if the issue still occurs.

If you still have the issue after re-installing, it's possible that Kodi has installed the skin from the local package cache instead of the repository where the updated .zips are.

To fix this, navigate to `...\addons\packages` and delete `skin.auramod.zip` before trying to install again.

**Comment by Ghostwithoutashell** [comment]
Looks like its fixed, the cache clearing was a bit annoying. also needed to clear app cache for Fen so it can repull the thumbnails. THank you for being so responsive. If i run into any other issues i will report them.
