### ISSUE TITLE
TV shows  / selecting episodes from main menu widget doesn't work for real file library items 

### ISSUE THREAD

**Issue by Travion1976** [SerpentDrago/skin.auramod#37]
Thanks for your work on the Aura Mod skin for Matrix. 
I am having issues selecting  a tv show and then entering the episode list. 
I have attached a pdf to see what happens.
Thanks a lot.
[Adding TV Shows.pdf](https://github.com/SerpentDrago/skin.auramod/files/6278546/Adding.TV.Shows.pdf)

**Comment by Travion1976** [comment]
This might be the same issue Dealz-416LS has posted.

**Comment by SerpentDrago** [comment]
FYI you can paste in images into comments on github . no need for the pdf .

i will try to replicate , what branch of auramod are you on ? Matrix or Testing?

**Comment by Travion1976** [comment]
Ok cool Thanks I will keep this in mind for the next time. 
I am using the Matrix compatible version.

**Comment by SerpentDrago** [comment]
> Ok cool Thanks I will keep this in mind for the next time.
> I am using the Matrix compatible version.

There is a Matrix Branch on github and a Testing branch on github . which zip are you using , Try using the zip from testing branch . 

![image](https://user-images.githubusercontent.com/21133858/114036074-bdd9bf80-984d-11eb-8e56-7f471308da5a.png)


![image](https://user-images.githubusercontent.com/21133858/114036117-c8945480-984d-11eb-8214-0d8f877b8871.png)


I'm on testing branch , and i can't replicate your issue

how are your library files generated ? are they real movies / shows (actual videos) or is it though tmdb library integration (strm files ) 

I'm testing with tmdb generated library items and can't replicate issue . 


https://user-images.githubusercontent.com/21133858/114036257-eb266d80-984d-11eb-8102-3ac1fd5b20e5.mp4

**Comment by Travion1976** [comment]
Thank you for the testing branch information - I will utilise this. I can see what happens and report back. 

The files are .mp4 files from a DVD stored on my synology nas. 
I am using tinymediamanager to organise artwork etc, so using "local information only".

**Comment by SerpentDrago** [comment]
ahh so real files , let me see if i can grab some real files and test with those .  the fact your using local meta info only shouldn't effect anything , but the fact your using real files could .so need to test that . give me a few .meanwhile you should be on testing .  Fix's will eventually be merged into "matrix" , but we wanted to test all the fix's in testing first for a bit

**Comment by SerpentDrago** [comment]
I actually just merged testing into Matrix branch , so your good to use a new zip from matrix branch , bumped version also to 1.0.4  . (its just testing branch merged , nothing new )

**Comment by Travion1976** [comment]
I just pulled from the test branch and installed this version.
Interesting enough it now does something different:
1 Click on TV Show
2 Receive the information screen
3 Click on "Episodes"
4 Jumps back to the main TV Shows list

**Comment by Dealz-416LS** [comment]
@Travion1976 what you're now experiencing looks like what @jojobrogess experienced with a comment [here](https://github.com/SerpentDrago/skin.auramod/issues/26#issuecomment-811576826) about it.

@SerpentDrago

**Comment by Travion1976** [comment]
Yep , that's correct - this is the same issue. 
Thanks for pointing this out.

**Comment by SerpentDrago** [comment]
> @Travion1976 what you now experiencing looks like what @jojobrogess experienced with a comment [here](https://github.com/SerpentDrago/skin.auramod/issues/26#issuecomment-811576826)
> 
> @SerpentDrago

I'm completly lost now . how is that the same issue , hes CLICKING episodes its not auto jumping back to main menu . The issue you linked to was closed ..

uggg , really frustrating when multiple issues are in a single issue post !!!!

**Comment by Travion1976** [comment]
https://user-images.githubusercontent.com/50074166/114046224-f5199200-9888-11eb-91cf-5a6848a1d8cc.mp4

**Comment by Travion1976** [comment]
Uploading a short vid

**Comment by SerpentDrago** [comment]
Ok did you CLICK episodes or did it just auto back out to main menu section ?

**Comment by Travion1976** [comment]
I Click on "Episodes" and it backs out to the main section

**Comment by Dealz-416LS** [comment]
Sounds like they click (short press) on Episodes, I think @inb4after got confused with my issue 31 and 26 that got closed. 26 and this 37 are the same local library file navigation bug.

**Comment by SerpentDrago** [comment]
Ok so different then the other issue , in that one he never clicks anything , just pulls up info screen and bam it backs out.

let me try to replicate with real video files in my library . 

What views are you using ? netflix home ?

**Comment by SerpentDrago** [comment]
> Sounds like they clicks (short press), I think @inb4after got confused with my issue 31 and 27 that got closed. 27 and this 37 are the same local library file navigation bug.

short press from main menu widget item , means it just defaults to opening info. instead of long press from widget item that pulls up context then going information from that  ,  from my understanding the issue was not CLICKING on episodes once info was open , only it would back out just pulling up info screen as it was loading .

Guys you have to be SPECIFIC and list ALL steps , dont' skip any or we can't replicate shit .  EVERY step and how you did something is important in debuging and replication

**Comment by Travion1976** [comment]
Yes, I am using Netflix Home Layout.

**Comment by Travion1976** [comment]
Let me know if you need any more information for me to provide.

**Comment by SerpentDrago** [comment]
Roger let me try to replicate , Again your  clicking on a widget item from a main menu section, widget  pointed to library tvshows titles ,  click *info is default and pulls up the info screen * , then you CLICK episodes ,, and it backs out to main menu widget . ?

**Comment by Travion1976** [comment]
Widget is pointing to my TV Shows library on NAS. See the screenshots attached.
-Click info is default and pulls up the info screen --> This must be a setting , maybe you can tell me where to look to confirm.
I go into the TV Shows -> Click on Tv Show -> Click on Episodes -> Backs out and jumps to TV Shows main list (Screen)

![IMG_2086](https://user-images.githubusercontent.com/50074166/114049223-9275c580-988b-11eb-827b-f8f587665f82.jpg)
![IMG_2087](https://user-images.githubusercontent.com/50074166/114049252-97d31000-988b-11eb-8b34-3dd6353345aa.jpg)
![IMG_2088](https://user-images.githubusercontent.com/50074166/114049265-999cd380-988b-11eb-9f3a-9ae6a8512e4b.JPG)

**Comment by SerpentDrago** [comment]
Replicated issue ! , only happens with REAL files  (non tmdb helper generated library items ) 

To replicate this issue , Add real media (tv show)  as a Video source , let it be scanned into library . I used TMDB show scraper for meta info . 

Set a main menu widget to point to Library > shows > titles 

Click one of those library items in the widget , which will pull up netflix info , then CLICK episodes . You will be returned to main menu widgets . 

Click one of the library items thats from tmdb helper generated library items (strm files) and the issue does NOT happen .

**Comment by SerpentDrago** [comment]
No promises when this gets fixed , but i consider it high priority as its a breaking issue with a main feature of the skin , thanks for the detailed info

**Comment by Travion1976** [comment]
Interesting ! 
OK cool, glad I could help providing this information.
I will keep my eyes open. Thanks again for all your dedicated work to this fantastic skin !

**Comment by jojobrogess** [comment]
Okay let me be clear, I have absolutely **no idea** what I'm doing when it comes to this code. 
Like none, but I started to wonder what was going on with this one. When I first updated from v18.9 to 19 (after I chaned the gui version to 15) the Auramod navigation skin part worked, but some of the component pieces did not(like skin helper service/widgets and navigation was a little buggy and slow especially with artwork).  
So I went searching for a newer version, and found this one. Once I updated I noticed this bug.
After posting an issue about it I started to wonder if there was a change to this version over the v18 I originally had, because in that version the navigation worked. Obviously I have already deleted the version I originally had, because why wouldn't I? lol idiot.   
So I then sifted through the commits and until I saw something that was changed.

Commit e3090b79b97a28db0345ac8dac575f837db86844 "Possible fix for "Episodes" button on Show items" that SerpentDrago committed on Aug 6, 2020. It looked to be either THE commit change or something near it that would lead me into understanding the coding for this skin better so I could at least attempt to rig it to work. I figured why not just revert the code to see if it would help me, it would take two seconds and it's written right there. 
Replace line 1421 in DialogVideoInfo-Includes.xml from the green section to the red section. 

FROM:
 
`<onclick condition="String.IsEqual(Skin.String(AddonContainer),false)">ActivateWindow(10025,$ESCINFO[ListItem.FileNameAndPath],return)</onclick>`

TO:

`<onclick condition="String.IsEmpty(ListItem.DBID) + String.IsEqual(Skin.String(AddonContainer),false)">ActivateWindow(10025,$ESCINFO[ListItem.FileNameAndPath],return)</onclick>`

So I did, and it seems to have worked. 

Now idk why this was changed, or even what the difference is. So I don't know if there is something else that breaks when you do this, because I only have/use real library files. But it seems to have fixed my "navigation" problem.

WHICH WAS(to be clear): While using the Netflix Style Home Layout and using real library files(samba share rpi 4 with exthd). I would click on any TV show, default selection method brings up tv show information screen, THEN selecting(clicking on) "episodes" would revert me back to the main menu screen. 

AFTER I CHANGED CODE: I click on any TV show, default selection method brings up tv show information screen, THEN selecting(clicking on) "episodes" brings me to the nextup episode/last episode viewed.

Hope this helps

**Comment by SerpentDrago** [comment]
> Okay let me be clear, I have absolutely **no idea** what I'm doing when it comes to this code.
> Like none, but I started to wonder what was going on with this one. When I first updated from v18.9 to 19 (after I chaned the gui version to 15) the Auramod navigation skin part worked, but some of the component pieces did not(like skin helper service/widgets and navigation was a little buggy and slow especially with artwork).
> So I went searching for a newer version, and found this one. Once I updated I noticed this bug.
> After posting an issue about it I started to wonder if there was a change to this version over the v18 I originally had, because in that version the navigation worked. Obviously I have already deleted the version I originally had, because why wouldn't I? lol idiot.
> So I then sifted through the commits and until I saw something that was changed.
> 
> Commit [e3090b7](https://github.com/SerpentDrago/skin.auramod/commit/e3090b79b97a28db0345ac8dac575f837db86844) "Possible fix for "Episodes" button on Show items" that SerpentDrago committed on Aug 6, 2020. It looked to be either THE commit change or something near it that would lead me into understanding the coding for this skin better so I could at least attempt to rig it to work. I figured why not just revert the code to see if it would help me, it would take two seconds and it's written right there.
> Replace line 1421 in DialogVideoInfo-Includes.xml from the green section to the red section.
> 
> FROM:
> 
> `<onclick condition="String.IsEqual(Skin.String(AddonContainer),false)">ActivateWindow(10025,$ESCINFO[ListItem.FileNameAndPath],return)</onclick>`
> 
> TO:
> 
> `<onclick condition="String.IsEmpty(ListItem.DBID) + String.IsEqual(Skin.String(AddonContainer),false)">ActivateWindow(10025,$ESCINFO[ListItem.FileNameAndPath],return)</onclick>`
> 
> So I did, and it seems to have worked.
> 
> Now idk why this was changed, or even what the difference is. So I don't know if there is something else that breaks when you do this, because I only have/use real library files. But it seems to have fixed my "navigation" problem.
> 
> WHICH WAS(to be clear): While using the Netflix Style Home Layout and using real library files(samba share rpi 4 with exthd). I would click on any TV show, default selection method brings up tv show information screen, THEN selecting(clicking on) "episodes" would revert me back to the main menu screen.
> 
> AFTER I CHANGED CODE: I click on any TV show, default selection method brings up tv show information screen, THEN selecting(clicking on) "episodes" brings me to the nextup episode/last episode viewed.
> 
> Hope this helps

Yeh good sluthing , i figured it was that modification that fucked it . That was to fix a issue when using NON real file and tmdb helper library items . before that "quick fix " that was not very well tested as you can see . if you clicked episodes they didn't work from a tmdb helper fake library file . (strm file ) . 

so to fix this for all types of files  , sometime me or someone else will have to go though those lines and add a new one with a different condition or something .

Your right on track ! you did good .  I just have not had the time to look into it is all . 

In my experience more were complaining and having issues with tmdb helper library files not working vs users with real files . so thats why it was never discovered at that time . most of the skin users historically for this skin , are using a combo of TMDB helper library items and or seren . 

Good job !

**Comment by SerpentDrago** [comment]
at least that used to be the case , i guess i'll go back and test it , with real files / tmdb helper files / addon content .

**Comment by inb4after** [comment]
@Travion1976 @jojobrogess @Dealz-416LS 

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

Please let us know your results, and if any new bugs occur.

**Comment by jojobrogess** [comment]
Thanks @inb4after !! Looks like this fixed the issue. At least for me.
I have NOT noticed anything unusual with the fix, but I'm like 5 minutes in..

PLUS it looks like if you add this fix into the "Ratings and Artwork" branch, it ALSO works. freaking yay.(i already added the line and tested it to see if it would operate correctly without my issue, and it does. idk if there's any other issues on that branch since it's a little bit of a bigger revision but regardless my issue is fixed on it.)

I'll run the testing branch for a couple days to see if any new bugs arise, but doubtful since you only added 1 line;
before I eventually switch back to the Ratings and Artwork branch, since it's such a beautiful and functional update.

Thanks again bro, seriously.

**Comment by SerpentDrago** [comment]
@jojobrogess  I've merged this also into Ratings tmdb helper branch , to keep it in sync with Matrix :) 

Should make it easier for you if testing and for us :0

**Comment by Travion1976** [comment]
System : Raspberry Pi 4B 8GB RAM
LibreElec

Hi guys, 
Thank you for the update. 
I tested with real library files - It works. Awesome.  
So which version should be utilised in order to have the latest update with fixes, just to make sure I don't report anything which has already been deployed in a latest version?
Thanks guys.

**Comment by SerpentDrago** [comment]
Work in progress , depends what your testing , but generally , always check if issue exists in Matrix branch . thats the main branch . side branches are for testing various fix's and patches and will eventually find there way into matrix.

**Comment by Travion1976** [comment]
ok cool. Thanks a lot.
