### ISSUE TITLE
Liked percent rating has changed 

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#60]
![20210427_215910](https://user-images.githubusercontent.com/76907836/116312586-8bfcae80-a7a4-11eb-8e79-683ae62f1ca8.jpg)

On the Matrix TMDB ratings branch the liked percent has changed, for example in this photo previously it would have labeled it as 83% liked in this example, it now says 8.3% could this please be looked at, most appreciated. Many thanks, running kodi 19 on nvidia shield pro

**Comment by SerpentDrago** [comment]
That's poster with overlay enabled right? Is the issue present with anything else?

Did this issue occur on tmdb ratings artwork branch before today's commits?

**Comment by JFG1000** [comment]
Yes also appears in showcase view i use, and yes this was also on the previous tmdb ratings branch version i forgot to make a post the other day

**Comment by SerpentDrago** [comment]
Ok this only happens on shows , unable to preproduce on movies . but get it on Shows . Funny enough it shows up first time correct then "changes" to have a dot between .

**Comment by SerpentDrago** [comment]
OK so , the  " liked percent "  shown for SHOWS was NEVER accurate to begin with it was converting a IMDB rating into a percent which is just wrong .. and inaccurate . when RT data was  not available.  RT is the only thing that has Percent liked  as IMDB is a 0-10 rating system. 

Then on top of that OMDB doesn't provide RT ratings for MOST shows , for legal reasons > https://github.com/omdbapi/OMDb-API/issues/147


I'm going to work on displaying it slightly different if RT data is not there .  

rather than "x% Liked",   to   "x out of 10"

Thoughts ? questions ? hatemail ? lol 

I have a fix so its back to how it was before this branch . but its just a IMDB rating converted , which is inaccurate

Or i could just have it simply not show if there is not a proper RT % rating provided by OMDB

**Comment by SerpentDrago** [comment]
"fixed" for now , we will revisit even doing this when there is no True liked percent rating  (RT rating ) available in the future
