### ISSUE TITLE
Trakt Manager - Netflix info Broken - Seren Show info level

### ISSUE THREAD

**Issue by SerpentDrago** [SerpentDrago/skin.auramod#72]
The Trakt Manager button for Seren Netflix info  EPISODE items is broken .

**Comment by Dealz-416LS** [comment]
Same issue reported [here](https://github.com/nixgates/plugin.video.seren/issues/456)?

Trakt Manager via Netflix Info for Episodes works fine for me including for Movies.

Shows will however give a Seren error.

There was a workaround with a minor modification to an auramod file but that stopped working with Seren 2.0.17 and later.

**Comment by inb4after** [comment]
@SerpentDrago @Dealz-416LS @JacopoV

Fixed in [Testing branch](https://github.com/SerpentDrago/skin.auramod/tree/Testing).

I'm pretty sure there is an underlying Seren issue, but for now we can use this quick-fix. 

In testing I only experienced this bug at the tvshow level. Episodes and movies are working correctly as @Dealz-416LS mentioned, needs confirmation though due to the issue title.

Please let us know your results and if any further bugs occur.

**Comment by Dealz-416LS** [comment]
@inb4after 

Thank you! Installed the Testing Branch and Trakt Manager for TV Show items now works in Netflix Info (no longer getting a Seren Error), Episodes and Movie items still work as before.

**Comment by SerpentDrago** [comment]
Testing Branch results 5/8/2021

Seren Movie /Netflix info  ( Widget >Seren >  movies > Most Popular )  
 Working ! 

Seren Episode/ Netflix info ( widget > seren > my shows > next up ) 
 Working ! 
 
 Seren Show / Netflix info (widget > seren > Shows > most popular ) 
 Workin ! 
 
 All seems good !

**Comment by JacopoV** [comment]
Thanks guys for looking into! And ofc for the fix @inb4after!

**Comment by itinerantmarshmallow** [comment]
I'll give the latest testing branch a go.

**Comment by SerpentDrago** [comment]
If testing use the ratingsplustesting branch

**Comment by inb4after** [comment]
Fixed in AuraMOD [Matrix branch](https://github.com/SerpentDrago/skin.auramod) v1.0.5
