### ISSUE TITLE
Graphic bug with Kodi on Demand

### ISSUE THREAD

**Issue by MikeKOD** [SerpentDrago/skin.auramod#77]
I have problems with appearing squares when searching from the KOD addon, I have attached photos and videos of the problem:

https://user-images.githubusercontent.com/52321149/117654603-41ad0180-b196-11eb-8c9d-2a966aa1a874.mp4

![photo_2021-05-10_13-40-55](https://user-images.githubusercontent.com/52321149/117654048-84baa500-b195-11eb-8c04-d0855b6ca311.jpg)

**Comment by SerpentDrago** [comment]
Your screenshots look nothing like Auramod Skin , i have 0 idea what your issue is or even what skin your running . what version of kodi your on or what version of supposedly auramod your using . or what "kodi on demand " even means 

Your going  to need to provide much more info and show more screens , cause again that doesn't look like auramod at all .

**Comment by jojobrogess** [comment]
I think he's talking about the addon KodionDemand https://github.com/kodiondemand/addon
which looks to be sometype of web browser, i cant really tell cuz the whole thing is in italian.

it looks like @wsx79 has added a couple issues/commits to that repository, might be smart to ask him 
since he's added issues/commits to this repository. he might have a keener eye on what's going on here. 

Ragardless this looks to be an addon error rather than a skin error to me.
