### ISSUE TITLE
Cast & More option to display kodi library content only

### ISSUE THREAD

**Issue by jojobrogess** [SerpentDrago/skin.auramod#78]
I was wondering if there was any way of setting the section inside `Cast & More` to only list items within my kodi library and not to display content that's not.

Example is of `Similiar` category but it's pretty much the same for cast, sets, recommended, director, year, and studio:

Netflix style homepage
![reommend](https://user-images.githubusercontent.com/17692472/117766210-105b2280-b1e4-11eb-8234-8aea55cca410.png)

Clicking on `Avengers Endgame`:
![castnmore](https://user-images.githubusercontent.com/17692472/117765863-7bf0c000-b1e3-11eb-8571-9d7a1b9cd4e4.png)

Then `Cast & More` and navigating down to `similiar`:
![similiar](https://user-images.githubusercontent.com/17692472/117765868-7e531a00-b1e3-11eb-9a8b-5eea99968fe0.png)
I don't currently have `Man of Steel` inside my library. The only movie I have in my library being display is `Captain Marvel`.

Then clicking on `Man of Steel`
![similiarbutt](https://user-images.githubusercontent.com/17692472/117765871-7eebb080-b1e3-11eb-9df7-e9bfb6bc5c4f.png)

Then clicking on `Play`
![play](https://user-images.githubusercontent.com/17692472/117767178-6b414980-b1e5-11eb-8974-6f44650afb66.png)

I'm positive this isn't bug, my guess would be that this is the process that some people use, I just think it's weird that there are movies as a whole being displayed when I do not have the content within my library. Same thing with the `Play` button being displayed when I do not have the content in my library currently. 

That's why I'm wondering if there's any way of getting that to **only** display content in which I have within my kodi library? 
Did I miss a setting or am I using this section wrong? any help or pointers would be greatly appreciated.

**Comment by inb4after** [comment]
The Cast & More item is directly calling the addon TMDBHelper, so any content you browse through is looked up on-the-fly and is not tied to your library.

I believe this is how it has always worked originally. I don't see why you would need to view Similar/Recommended/By Genre etc. of your library items that you're planning on watching/have already watched, when you can set up widgets for those library items.

The emphasis of Cast & More is for discovery (extended info) rather than browsing and playing the library.

As for playing them, you can set up players within TMDBHelper and it will play the local library file if it exists or pass to an addon, like a "smart" play option.

**Comment by SerpentDrago** [comment]
This is not something that will ever happen at least not on auramods side and you are probably the only one ever to request this.

If it would happen it would have to be a specific feature of tmdb helper that would only show content already in library.


Kodi already has smart playlists and skin helper has specific sections to help with local file discovery.

Sorry not happening. Have a good day
