### ISSUE TITLE
"Returning Series"  doesn't fit in  widget 'poster' style  'showcase overlay' enabled   for Show items

### ISSUE THREAD

**Issue by SerpentDrago** [SerpentDrago/skin.auramod#89]
Some addons / content , supply enough info , such as Total length , on even Shows (instead of just episodes) causing a fit issue 

Prob need a option to not show it , or redesign it so it fits better if available 

![image](https://user-images.githubusercontent.com/21133858/117886552-616b2500-b27d-11eb-8b5a-f113fbb1a782.png)

It quick testing the only addon i know of that provides enough info to display this issue is Fen , the above is a widget Poster style with showcase overlay enabled pointed to Fen > TV shows > popular

**Comment by SerpentDrago** [comment]
My suggestion is to just remove it entirely from any "show" content type ,  as that widget style overlay displays differently if its a movie vs show vs episode object .. and looks fine on all the other types

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/120321008-cb8d4d80-c2b0-11eb-9dc9-ae611efa2ea9.MOV

Just noticed on 1.0.15 it’s now also happening with venom which didn’t happen before returning series being cut off ,, but on poster style with showcase overlay using venom the returning series is not cut off ,,made a short video to try to explain a little better,, it was working on 1.0.13

**Comment by xyzfre** [comment]
From what I tested so far seems to be happening on poster showcase view but only after you click on a TV show and the seasons show up that’s where the returning series gets cut off,, I know using Fen this has always been a issue but not with Venom

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/120324520-bb776d00-c2b4-11eb-8dc8-f5a413fb719e.MOV
Here’s another video, I try to explain the best that I can

**Comment by xyzfre** [comment]
Maybe if there’s a way to change it just to say Returning and remove the word Series

**Comment by jojobrogess** [comment]
I think the only options are to either resize everything just to fit these two expressions,
Or remove/rename them. 
I'd rather not loose a feature so I think that renaming and maybe a slight resizing if it needs it, is the best way to go.

Plus this was just $LOCALIZE'd in commit https://github.com/SerpentDrago/skin.auramod/commit/c22f6767359d919ee72bc965de7619b734c9c227 ,  so now it can be easily changed.

Possible Series values are:
`Returning Series`
`Planned`
`In Production`
`Ended`
`Canceled`
`Pilot`


> ![image](https://user-images.githubusercontent.com/21133858/117886552-616b2500-b27d-11eb-8b5a-f113fbb1a782.png)

Looks like the space provided can only support 10-11 characters.(might need to be slightly bigger to make 11 fit fully)
So both `Returning Series`(16) and `In Production`(13) would cause this to bug out.

So that things don't have to be resized or removed:
`Returning Series` can be changed to `Returning`(9).
`In Production` can be changed to `Producing`(9) or `Filming`(7).

But a slight window resize with maybe a font resize for that particular `ListItem.Status`/window might do the trick as well.

Just a suggestion though.

**Comment by inb4after** [comment]
Fixed in latest commit

**Comment by inb4after** [comment]
Season and duration boxes will be re-worked at a later date so we can fit the localized strings too.
